# Generated by Django 5.2.3 on 2025-06-30 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Nominal')),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], max_length=3, verbose_name='Moneda')),
                ('gastos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gastos')),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de Interés (%)')),
                ('tipo_tasa', models.CharField(choices=[('nominal', 'Nominal'), ('efectiva', 'Efectiva')], max_length=20, verbose_name='Tipo de Tasa')),
                ('capitalizacion', models.IntegerField(blank=True, null=True, verbose_name='Capitalización')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('tipo_periodo_gracia', models.CharField(choices=[('ninguno', 'Ninguno'), ('total', 'Total (solo intereses)'), ('parcial', 'Parcial (sin pagos)')], default='ninguno', max_length=10, verbose_name='Tipo de Período de Gracia')),
                ('duracion_gracia', models.IntegerField(default=0, verbose_name='Duración de Gracia (meses)')),
                ('metodo_amortizacion', models.CharField(default='Francés', max_length=50, verbose_name='Método de Amortización')),
                ('frecuencia_pagos', models.IntegerField(choices=[(12, 'Mensual (12 pagos/año)'), (6, 'Bimestral (6 pagos/año)'), (4, 'Trimestral (4 pagos/año)'), (3, 'Cuatrimestral (3 pagos/año)'), (2, 'Semestral (2 pagos/año)'), (1, 'Anual (1 pago/año)')], verbose_name='Frecuencia de Pagos')),
                ('precio_mercado', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Precio de Mercado (%)')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Bono',
                'verbose_name_plural': 'Bonos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
