# Generated by Django 5.2.3 on 2025-07-02 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Nominal')),
                ('valor_comercial', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Comercial')),
                ('num_anios', models.IntegerField(verbose_name='Nº de Años')),
                ('frecuencia_cupon', models.IntegerField(choices=[(12, 'Mensual (12 pagos/año)'), (6, 'Bimestral (6 pagos/año)'), (4, 'Trimestral (4 pagos/año)'), (3, 'Cuatrimestral (3 pagos/año)'), (2, 'Semestral (2 pagos/año)'), (1, 'Anual (1 pago/año)')], verbose_name='Frecuencia del cupón')),
                ('dias_por_anio', models.IntegerField(choices=[(360, '360 días'), (365, '365 días')], verbose_name='Días por Año')),
                ('tipo_tasa_interes', models.CharField(choices=[('nominal', 'Nominal'), ('efectiva', 'Efectiva')], max_length=10, verbose_name='Tipo de Tasa de Interés')),
                ('capitalizacion', models.IntegerField(blank=True, null=True, verbose_name='Capitalización')),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de interés (%)')),
                ('tasa_anual_descuento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa anual de descuento (%)')),
                ('impuesto_renta', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Impuesto a la Renta (%)')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('porcentaje_prima', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Prima')),
                ('porcentaje_estructuracion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Estructuración')),
                ('porcentaje_colocacion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Colocación')),
                ('porcentaje_flotacion', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Flotación')),
                ('porcentaje_cavali', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% CAVALI')),
                ('metodo_amortizacion', models.CharField(default='Francés', max_length=50, verbose_name='Método de Amortización')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Bono',
                'verbose_name_plural': 'Bonos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
