# Generated by Django 5.2.3 on 2025-06-28 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('metodo_amortizacion', models.CharField(choices=[('FRANCES', 'Francés'), ('ALEMAN', 'Alemán'), ('AMERICANO', 'Americano')], default='FRANCES', max_length=10)),
                ('moneda', models.CharField(max_length=3)),
                ('tipo_tasa', models.CharField(choices=[('NOMINAL', 'Nominal'), ('EFECTIVA', 'Efectiva')], max_length=8)),
                ('frecuencia_pagos', models.IntegerField()),
                ('gastos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capitalizacion', models.IntegerField(blank=True, null=True)),
                ('periodo_gracia', models.DateField(blank=True, null=True)),
                ('precio_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
