# Generated by Django 5.2.3 on 2025-06-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bond',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='bond',
            name='metodo_amortizacion',
            field=models.CharField(default='Francés', max_length=50),
        ),
        migrations.AlterField(
            model_name='bond',
            name='precio_mercado',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bond',
            name='tipo_tasa',
            field=models.CharField(max_length=20),
        ),
    ]
