# Generated by Django 5.2.3 on 2025-07-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_alter_bond_impuesto_renta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bond',
            name='periodos_gracia',
        ),
        migrations.RemoveField(
            model_name='bond',
            name='tiene_plazo_gracia',
        ),
        migrations.RemoveField(
            model_name='bond',
            name='tipo_gracia',
        ),
        migrations.AlterField(
            model_name='bond',
            name='impuesto_renta',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Impuesto a la Renta (%)'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='porcentaje_cavali',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% CAVALI'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='porcentaje_colocacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Colocación'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='porcentaje_estructuracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Estructuración'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='porcentaje_flotacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Flotación'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='porcentaje_prima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Prima'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='tasa_anual_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa anual de descuento (%)'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de interés (%)'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='valor_comercial',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Comercial'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='valor_nominal',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Nominal'),
        ),
    ]
