# Generated by Django 5.2.3 on 2025-07-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_remove_bond_periodos_gracia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='periodos_gracia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Periodos de Gracia'),
        ),
        migrations.AddField(
            model_name='bond',
            name='tiene_plazo_gracia',
            field=models.BooleanField(default=False, verbose_name='¿Tiene plazo de gracia?'),
        ),
        migrations.AddField(
            model_name='bond',
            name='tipo_gracia',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('parcial', 'Parcial'), ('total', 'Total')], max_length=10, null=True, verbose_name='Tipo de Gracia'),
        ),
    ]
